---
year: '2014'
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
shortname: ICGI
booktitle: The 12th International Conference on Grammatical Inference
volume: 34
start: 2014-09-17
end: 2014-09-19
published: 2014-08-30
sections:
- name: preface
  title: Preface
- name: invited
  title: Invited Talks
- name: default
  title: Accepted Papers
layout: proceedings
publisher: PMLR
series: Proceedings of Machine Learning Research
issn: 1938-7228
id: ICGI-2014
month: 0
cycles: false
editor:
- given: Alexander
  family: Clark
- given: Makoto
  family: Kanazawa
- given: Ryo
  family: Yoshinaka
title: Proceedings of Machine Learning Research
description: |
  The 12th International Conference on Grammatical Inference
    Held in Kyoto, Japan on 17-19 September 2014

  Published as Volume 34 by the Proceedings of Machine Learning Research on 30 August 2014.

  Volume Edited by:
    Alexander Clark
    Makoto Kanazawa
    Ryo Yoshinaka

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 17--19 Sep
url: http://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v34"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
style: pmlr
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v34
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: International Conference on Grammatical Inference
  url: http://www.iip.ist.i.kyoto-u.ac.jp/icgi2014/
  location: Kyoto, Japan
  dates:
  - 2014-09-17
  - 2014-09-18
  - 2014-09-19
  number: 12
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
